# Generated by Django 4.0.3 on 2022-04-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog/image/')),
                ('title', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('webinar', 'WebInar'), ('report', 'Report')], max_length=128)),
                ('next', models.CharField(default='Read blog', max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('company_size', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500')], max_length=128)),
                ('industry', models.CharField(choices=[('1', 'Agriculture'), ('2', 'Banking & Finance'), ('3', 'Business Services & Software')], max_length=128)),
                ('job_role', models.CharField(choices=[('1', 'C-Suite'), ('2', 'VP')], max_length=128)),
                ('country', models.CharField(choices=[('us', 'United States'), ('albania', 'Albania')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature/image/')),
                ('icon', models.FileField(upload_to='feature/icons/')),
                ('icon_background', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=255)),
                ('testimonial_description', models.TextField(max_length=255)),
                ('testimonial_author', models.CharField(max_length=128)),
                ('author_designation', models.CharField(max_length=128)),
                ('testimonial_logo', models.ImageField(upload_to='features/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Marketingfeature/image/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product')),
                ('hero_image', models.FileField(upload_to='product/hero')),
                ('title', models.CharField(max_length=155)),
                ('name', models.CharField(max_length=155)),
                ('logo', models.FileField(upload_to='product/logo')),
                ('description', models.TextField(max_length=255)),
                ('bg_color', models.CharField(default='#fff', max_length=10)),
                ('button_bg_color', models.CharField(default='#fff', max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('image', models.FileField(upload_to='reviews')),
                ('play', models.FileField(upload_to='reviews')),
                ('logo', models.FileField(upload_to='reviews/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials')),
                ('logo', models.FileField(blank=True, null=True, upload_to='testimonials\\logo')),
                ('description', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=125)),
                ('role', models.CharField(max_length=125)),
                ('company_name', models.CharField(max_length=125)),
                ('is_featured', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='customers')),
                ('white_image', models.FileField(blank=True, null=True, upload_to='customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
        ),
    ]
